### ISSUE TITLE
Fields

### ISSUE THREAD

**Issue by BurlesonBrad** [stezu/stripe-for-woocommerce#69]
Stephen, I'm digging through the files here, to find this, but.........

## Where's the file that controls the 'type' for the credit card field?
![stephen-type-tel](https://cloud.githubusercontent.com/assets/6208757/8651966/892d8bf8-2941-11e5-9748-a0cb7cadfced.jpg)
After reading a few Lema articles *(and a bit more across the web)* & actually testing things out, it really does make a lot of sense that people on mobile & tablet should have the **correct keyboard** appear.
Hence, when we know that they're about to type **numbers**, we should display the **number keypad**.
*The same goes for email fields as well, but that's not part of this plugin.*
If we simply change the input type from *text* to **tel**, the same validation happens & the same functions happen. The only difference is that the end-user gets a **much** better, easier, and more efficient experience when they are checking out on a mobile device or a tablet.

**Comment by stezu** [comment]
The credit card form is handled by WooCommerce directly [here](https://github.com/woothemes/woocommerce/blob/master/includes/abstracts/abstract-wc-payment-gateway.php#L290-L328). You could maybe add that with JavaScript or use the woocommerce_credit_card_form_fields filter. I don't want to mess with that form in this plugin since I think it'll cause more issues than it solves.

**Comment by BurlesonBrad** [comment]
![2015-07-13 21 28 57](https://cloud.githubusercontent.com/assets/6208757/8665755/3b6dceca-29ad-11e5-80c9-45021ae1428e.png)
Man that looks SHARP! Thanks @stezu :+1:
